WanderWIKI/src/java/org/wanderWiki/beans/cardModel.java
/*  Bean zur Ermittlung von Geodaten zu einem eingegebebn Punkt
    und Anzeige der Karte via gmaps4JSF
    erstellt: Andre Hantke
*/
package org.wanderWiki.beans;

import com.google.code.geocoder.Geocoder;
import com.google.code.geocoder.GeocoderRequestBuilder;
import com.google.code.geocoder.model.GeocodeResponse;
import com.google.code.geocoder.model.GeocoderRequest;
import com.google.code.geocoder.model.GeocoderResult;
import com.google.code.geocoder.model.GeocoderStatus;
import com.googlecode.gmaps4jsf.component.common.Position;
import com.googlecode.gmaps4jsf.component.map.Map;
import com.googlecode.gmaps4jsf.component.marker.Marker;
import java.io.IOException;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.RequestScoped;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ValueChangeEvent;

@ManagedBean
@SessionScoped
@RequestScoped
public class cardModel {
    
    private String Stadt;
    private double latitude;
    private double longitude;
    private int zoom;
    
    private Map map;   
    
    public cardModel(){
       
        this.Stadt="Münster";
        this.latitude=51.960453;
        this.longitude=7.625470;
        
        
    }
    
    public void gib_alle_marker(){
        
     
              
        for (UIComponent kind : map.getChildren()) {
            Marker marker = (Marker) kind;
            System.out.println("marker: "+marker.getLatitude());
        }

        
        
    }
    
     public Map getMap() {
        return map;
    }

    //setzen der Defaultwerte für die Karte
    //hier Münster 
    public void setMap(Map map) {
        this.map = map;
        map.setLatitude("51.960453");
        map.setLongitude("7.625470");
    }

    public String getStadt() {
        return Stadt;
    }

    public void setStadt(String Stadt) {
        this.Stadt = Stadt;
    }

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public int getZoom() {
        return zoom;
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }
   

    //Lade Karte entsprechend der eingabe in ein Input Feld
    //@autor: Andre Hantke
    //der eingegebene Wert in ein Inputfeld
    //wird hier mit Hilfe des Geocoders in Latitude und Longitude umgewandelt
    //anschließend kann die Karte aktualisiert werden
    //der Zoom kann gesetzt werden und 
    //der Kartenausschnitt kann aktualisiert werden
    public void loadCard(){             
        Geocoder geocoder = new Geocoder();  
        //Request
        GeocoderRequest geocoderRequest = new GeocoderRequestBuilder()
                                                .setAddress(this.Stadt) // location
                                                .setLanguage("de") // language
                                                .getGeocoderRequest();
        //response
        GeocodeResponse geocoderResponse;
        //Response Auflösung
        try {
            geocoderResponse = geocoder.geocode(geocoderRequest);
            if (geocoderResponse.getStatus() == GeocoderStatus.OK
              & !geocoderResponse.getResults().isEmpty()) {
              GeocoderResult geocoderResult = 
                geocoderResponse.getResults().iterator().next();
                com.google.code.geocoder.model.LatLng latitudeLongitude =
                geocoderResult.getGeometry().getLocation();
              Float[] coords = new Float[2];
              this.latitude = latitudeLongitude.getLat().doubleValue();
              this.setLatitude(latitudeLongitude.getLat().doubleValue());
              this.longitude = latitudeLongitude.getLng().doubleValue();
              this.setLongitude(latitudeLongitude.getLng().doubleValue());
              this.setZoom(10);
        }
     } catch (IOException ex) {
       ex.printStackTrace();
     }
        String lati = new Double(this.latitude).toString();
        String longi = new Double(this.longitude).toString();
        
        //setzen des Models der Karte
        map.setLatitude(lati);
        map.setLongitude(longi);
        map.setZoom("13");
       
        //Setzen des Markers
        Marker m1 = new Marker();
        m1.setDraggable("true");
        m1.setLatitude(lati);
        m1.setLongitude(longi);
        
        //clear Karte und füge die Kinder neu hinzu
        map.getChildren().clear();
        map.getChildren().add(m1);
        
//        RequestContext ctx = RequestContext.getCurrentInstance();
//        ctx.update("contentform:karte");
        //Ausgabe
        System.out.println("(Stadt: " + this.Stadt + "Lat: " + this.latitude + "Lon: " + this.longitude);
    }
    
    public void legePunktFest(ValueChangeEvent event)throws AbortProcessingException {
        Position value = (Position) event.getNewValue();
    	
        Marker source = (Marker) event.getSource();
        String markerID = source.getJsVariable();
        
        String message = markerID + " is moved to the following location: " + value.toString();
        
        System.out.println(message);
        System.out.println("GNAMPF");
        System.out.println("lat:"+this.latitude+" long:"+this.longitude);  
        
    }
}

WanderWIKI/src/java/org/wanderWiki/beans/myAccountBean.java
/**
 * *****************************************************
 * Bean zur Verwaltung des Accounts eines Users
 * erstellt: 05.12.2015 
 * Verantwortlich: Andre Hantke
 * 
 * ******************************************************
 */
package org.wanderWiki.beans;

import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.ResourceBundle;
import javax.faces.application.FacesMessage;
import javax.faces.bean.ManagedBean;
import javax.faces.bean.ManagedProperty;
import javax.faces.bean.SessionScoped;
import javax.faces.context.FacesContext;
import javax.faces.event.AbortProcessingException;
import javax.faces.event.ValueChangeEvent;
import javax.faces.event.ValueChangeListener;
import org.primefaces.context.RequestContext;
import org.wanderWiki.DAO.UsersDAOJPA;
import org.wanderWiki.entities.Users;

/**
 *
 * @author Andre
 */
@ManagedBean
@SessionScoped
public class myAccountBean{
    
    //um den eingeloggten User zu bekommen und alle 
    //seine Daten
    @ManagedProperty(value="#{loginBean}")
    private loginBean loginBean;
    
    //um die Internationalisierung auch hier zu nutzen
    @ManagedProperty(value="#{internationalButton}")
    private internationalButton internationalButton;

    //Sprache
    private List<String> language;
    //Rollstuhl
    private boolean wheelchair;    
    //Name
    private String name;
    //Email
    private String email;
    //Passwort
    private String pass;
    //Laufgeschwindiglkeit
    private List<String> walking;
    //Interessen
    private List<String> interests;
    
    //ausgewählte Laufgeschwindigkeit
    private String selectedwalking;
    private boolean renderpasswortaendern;
    private boolean renderpasswortinput;
    
    //Konstruktor
    public myAccountBean(){
        
        this.renderpasswortaendern=true;
        this.renderpasswortinput=false;
    }
    
    public List<String> getLanguage() {
        return language;
    }
    
    public internationalButton getInternationalButton() {
        return internationalButton;
    }

    public void setInternationalButton(internationalButton internationalButton) {
        this.internationalButton = internationalButton;
    }

    public void setLanguage(List<String> language) {
        this.language = language;
    }
    
    public List<String> getWalking() {
        return walking;
    }

    public List<String> getInterests() {
        return interests;
    }

    public void setInterests(List<String> interests) {
        this.interests = interests;
    }

    public void setWalking(List<String> walking) {
        this.walking = walking;
    }
    

    public String getSelectedwalking() {
        return selectedwalking;
    }

    public void setSelectedwalking(String selectedwalking) {
        this.selectedwalking = selectedwalking;
    }

    public boolean isRenderpasswortinput() {
        return renderpasswortinput;
    }

    public void setRenderpasswortinput(boolean renderpasswortinput) {
        this.renderpasswortinput = renderpasswortinput;
    }

    public boolean isRenderpasswortaendern() {
        return renderpasswortaendern;
    }

    public void setRenderpasswortaendern(boolean renderpasswortaendern) {
        this.renderpasswortaendern = renderpasswortaendern;
    }

    public loginBean getLoginBean() {
        return loginBean;
    }

    public void setLoginBean(loginBean loginBean) {
        this.loginBean = loginBean;
    }
    
    public String getPass() {
        return pass;
    }

    public void setPass(String pass) {
        this.pass = pass;
    }

   
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setLanguage(String language) {
        //nix setzen, erfolgt via Konstruktor
    }

    public boolean isWheelchair() {
        return wheelchair;
    }

    public void setWheelchair(boolean wheelchair) {
        this.wheelchair = wheelchair;
    }
    
    //Drowp Down Interesse füllen je nach Sprache 
    public void insertInterest(){
        Locale l = internationalButton.getLocale();
        FacesContext.getCurrentInstance().getViewRoot().setLocale(l);
        ResourceBundle rb = ResourceBundle.getBundle("org.wanderWiki.language/messages",FacesContext.getCurrentInstance().getViewRoot().getLocale());
            interests= new ArrayList();
            interests.add(rb.getString("keinInteresse"));
            interests.add(rb.getString("geographisch"));
            interests.add(rb.getString("historisch"));
            interests.add(rb.getString("kulturell"));
            interests.add(rb.getString("religiös"));
            this.wheelchair=false;
            language=new ArrayList();
            language.add("de");
            language.add("en");
    }
        
    //Drowp Down Laufgeschwindigkeit füllen je nach Sprache 
    public void walkingSpeed(){
        Locale l = internationalButton.getLocale();
        FacesContext.getCurrentInstance().getViewRoot().setLocale(l);
        ResourceBundle rb = ResourceBundle.getBundle("org.wanderWiki.language/messages",FacesContext.getCurrentInstance().getViewRoot().getLocale());
        walking = new ArrayList();
        walking.add(rb.getString("langsam"));
        walking.add(rb.getString("normal"));
        walking.add(rb.getString("schnell"));
    }    
    
    public void loadContent(){
        walkingSpeed();
        insertInterest();
    }

    //wenn Locale englisch -> deutsche Persisitierung
    public void updateUser(){
        FacesContext ctx = FacesContext.getCurrentInstance();
        ResourceBundle rb = ResourceBundle.getBundle("org.wanderWiki.language/messages", ctx.getViewRoot().getLocale());
        System.out.println("Locale:.:::" + ctx.getViewRoot().getLocale());
        UsersDAOJPA udj = new UsersDAOJPA();
        if(loginBean.getLoggedinUser().getInterest().equals("no interest")){
            loginBean.getLoggedinUser().setInterest("kein Interesse");
        }else{
            if(loginBean.getLoggedinUser().getInterest().equals("geographical")){
                loginBean.getLoggedinUser().setInterest("geographisch");
            }else{
                if(loginBean.getLoggedinUser().getInterest().equals("historical")){
                    loginBean.getLoggedinUser().setInterest("historisch");
                }else{
                    if(loginBean.getLoggedinUser().getInterest().equals("cultural")){
                        loginBean.getLoggedinUser().setInterest("kulturell");
                    }else{
                        if(loginBean.getLoggedinUser().getInterest().equals("religious")){
                            loginBean.getLoggedinUser().setInterest("religiös");
                        }
                    }
                }
            }
        }
        
        if(loginBean.getLoggedinUser().getWalkingSpeed().equals("slow")){
            loginBean.getLoggedinUser().setWalkingSpeed("langsam");
        }else{
            if(loginBean.getLoggedinUser().getWalkingSpeed().equals("normal")){
                loginBean.getLoggedinUser().setWalkingSpeed("normal");
            }else{
                 if(loginBean.getLoggedinUser().getWalkingSpeed().equals("fast")){
                    loginBean.getLoggedinUser().setWalkingSpeed("schnell");
                 }
            }
        }
        
        //Update der Daten des eingeloggten Users
        udj.update(loginBean.getLoggedinUser());
        
        ctx.addMessage(null, new FacesMessage(FacesMessage.SEVERITY_INFO, rb.getString("datenchanged"), null));
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('myAccount').hide()");
    }
    
    //Passwort wechseln, anzeigen seperater Komponenten
    public void changePassword(){
        this.renderpasswortaendern=false;
        this.renderpasswortinput=true;
    }
    
    //Abbrechen
    public void abbort(){
        this.renderpasswortaendern=true;
        this.renderpasswortinput=false;
    }
    
    //Dialog schließen
    public void closeDialog(){
       FacesContext c = FacesContext.getCurrentInstance();
        
        if(internationalButton.getLoc().equals("de")){
            c.getViewRoot().setLocale(Locale.GERMAN);    
            ResourceBundle rb = ResourceBundle.getBundle("org.wanderWiki.language/messages", c.getViewRoot().getLocale());
        }else{
            if(internationalButton.getLoc().equals("en")){
                c.getViewRoot().setLocale(Locale.ENGLISH);    
                ResourceBundle rb = ResourceBundle.getBundle("org.wanderWiki.language/messages", c.getViewRoot().getLocale());
            }
        }
        RequestContext context = RequestContext.getCurrentInstance();
        context.execute("PF('myAccount').hide()");
    }
    
    public void changeNewPassword(){
        loginBean.getLoggedinUser().setPasswordHash(pass);
        this.renderpasswortaendern=true;
        this.renderpasswortinput=false;
    }
    
    
   
    
    
    
}

WanderWIKI/web/resources/basics/POIDatatable.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* kann verwendet werde um sich die Einträge in der 
* Datenbank in einer Tabelle anzuschauen
* Verantwortlich: Andre Hantke
* Version 1.0
********************************************************/
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:m="http://code.google.com/p/gmaps4jsf/">
    <h:head>
        <title> </title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    </h:head>
    <h:body>
        <h:form id="form1">
            <p:commandButton value="Click" action="#{poiBean.loadData()}" update="lab"/>
            <!--<p:outputLabel id="lab" value="#{poiBean.street}"/>-->
            <p:separator/>
            <p:dataTable id="lab" var="POI" value="#{poiBean.liste}">
                <p:column headerText="ID">
                    <h:outputText value="#{POI.idPlaces}"/>
                </p:column>

                <p:column headerText="Type">
                    <h:outputText value="#{POI.type}"/>
                </p:column>

                <p:column headerText="Name">
                    <h:outputText value="#{POI.name}"/>
                </p:column>

                <p:column headerText="Längengrad">
                    <h:outputText value="#{POI.longtitude}"/>
                </p:column>

                <p:column headerText="Breitengrad">
                    <h:outputText value="#{POI.latitude}"/>
                </p:column>

                <p:column headerText="Altitude">
                    <h:outputText value="#{POI.altitude}"/>
                </p:column>

                <p:column headerText="Strasse">
                    <h:outputText value="#{POI.street}"/>
                </p:column>

                <p:column headerText="PLZ">
                    <h:outputText value="#{POI.postalCode}"/>
                </p:column>

                <p:column headerText="Stadt">
                    <h:outputText value="#{POI.city}"/>
                </p:column>
            </p:dataTable>                      
        </h:form>     
    </h:body>
</html>

WanderWIKI/web/resources/basics/footer.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* erstellt am 08.06.2014
* Footer
* Verantwortlich: Andre Hantke
* Version 0.5
********************************************************/
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <f:loadBundle id="languageBase" basename="#{internationalButton.value}" var="messages"/>
    <h:head>
        <title>FOOTER</title>
    </h:head>
    <h:body>    
        <ui:composition>
            <h:panelGrid columns="3" border="0">
                <h:form>
                    <p:commandLink value="#{messages['Startseite']}" action="#{navigationBean.goToStartseite()}" style="color: white" ajax="false"/>
                    <p:spacer width="15px"/>
                    <p:commandLink value="#{messages['Hilfe']}" action="#{navigationBean.goToHilfe()}" style="color: white" ajax="false"/>
                </h:form>
            </h:panelGrid>
        </ui:composition>
    </h:body>
</html>

WanderWIKI/web/resources/basics/loggedHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* erstellt am 08.06.2014
* Template mit Willkommensgruß nach erfolgreichen login!
* Verantwortlich: Andre Hantke
* Version 1.0
********************************************************/
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
   
    <f:loadBundle id="languageBase" basename="#{internationalButton.value}" var="messages"/>
    <h:head>
        <title> </title>
         <f:facet name="last">
            <h:outputStylesheet library="css" name="growl.css"/>
        </f:facet>       
    </h:head>
    <h:body>
        <ui:composition>
        <h:form style="margin-left: auto; margin-right: 0px; ">
           <p:growl id="growl" showDetail="true"  autoUpdate="true" class="ui-growl"/>                                      
            <p:panel widgetVar="panel1" id="panelLogin" style="border-color: transparent; height: 90px;">
                <h:panelGrid columns="5" style="width: auto;">
                    <p:selectOneMenu id="selectLanguage" valueChangeListener="#{internationalButton.processValueChange}" onchange="this.form.submit()" value="#{internationalButton.loc}">
                        <f:selectItems value="#{internationalButton.country}"/>
                    </p:selectOneMenu>
                    <p:spacer width="15px"/>
                    <p:outputLabel value="#{messages['willkommen2']} #{loginBean.name}"/>
                    <p:spacer width="15px" height="0px"/>
                    <p:commandButton value="Logout" actionListener="#{loginBean.user_ausloggen()}" action="index.xhtml" ajax="false"/>
                    <p:spacer/>
                    <p:spacer/>
                    <p:commandLink value="#{messages['meinkonto']}" action="#{dialogBean.showMyAccountDialog()}" style="font-size: 15px;  color: teal;"/>
                </h:panelGrid>
            </p:panel>                                  
        </h:form>  
        </ui:composition>
    </h:body>
</html>

WanderWIKI/web/resources/basics/loginHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* erstellt am 08.06.2014
* Login Formular rechts oben inkl. Internationalsierung
* Verantwortlich: Andre Hantke
* Version 1.0
********************************************************/
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">

    <f:loadBundle id="languageBase" basename="#{internationalButton.value}" var="messages"/>
    <h:head>
        <title> </title>
        <meta charset="utf-8"></meta>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></meta>
        <meta name="description" content=""></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>       
    </h:head>    
    <h:body>
        <ui:composition>
            <p:panel widgetVar="panel1" id="panelLogin" style="border-color: transparent; height: 90px;">  
            <h:form>
                <p:growl id="growl" showDetail="true" class="ui-growl" autoUpdate="true"/>                                      
                 
                    <!--TODO: Alternative zum panelgrid verwenden damit das Desgin bei schmalerern Bildschirmen nicht zerschossen wird-->
                    <h:panelGrid  columns="4" cellpadding="5" style="overflow-y: hidden; width: auto; margin-left: auto; " >    
                        <p:selectOneMenu id="selectLanguage" valueChangeListener="#{internationalButton.processValueChange}" onchange="this.form.submit()" value="#{internationalButton.loc}" style="border-color: transparent;">
                            <f:selectItems id="items" value="#{internationalButton.country}"/>
                        </p:selectOneMenu>
                        
                            <p:inputText id="mail" type="text" placeholder="Email" value="#{loginBean.email}" alt=""/>
                            <p:inputText id="pass" type="password" placeholder="#{messages['Passwortlang']}" value="#{loginBean.passwort}" alt=""/>
                           
                            <p:commandButton value="Login" actionListener="#{loginBean.checkUserLogin()}" action="index.xhtml" ajax="false"/>  
                               
                    </h:panelGrid>   
            </h:form> 
            <h:form> 
                <h:panelGrid  columns="2" cellpadding="5" style="overflow-y: hidden; width: auto; margin-left: auto; " >             
                   <p:commandLink value="#{messages['Registrierung']}?" action="#{dialogBean.showRegistrationDialog()}" style=" font-size: 15px;  color: teal;"/>
                   <p:commandLink value="#{messages['passvergessen']}" action="#{dialogBean.showPasswordNewDialog()}" style="font-size: 15px;  color: teal;"/>
                   
                </h:panelGrid> 
            </h:form> 

            </p:panel>                                   
            <!--</h:form>-->
        </ui:composition>
    </h:body>
</html>

WanderWIKI/web/resources/basics/mapcard.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* Facelet zur Eingabe einer Stadt oder ähnliches
* mit Anzeige auf Karte
* gehört zur Bean cardModel!
* Verantwortlich: Andre Hantke
* Version 1.0
********************************************************/
-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:m="http://code.google.com/p/gmaps4jsf/">
    <h:head>
        <title>Karte</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
                <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?sensor=true">
         </script>
    </h:head>
    <h:body>
        <h:form>
            <p:panel>
                <h:outputLabel value="Stadt:" ></h:outputLabel>
                <p:spacer width="15px"/>
                <p:inputText value="#{cardModel.stadt}"/>
                <p:spacer width="30px"/>
                <p:commandButton value="GO!" ajax="false" action="#{cardModel.loadCard()}" update="karte"/>
            </p:panel>
            <p:panel id="karte">
                <m:map width="1000px" height="550px" binding="#{cardModel.map}" partiallyTriggered="false">
                 <m:marker>
                     <m:htmlInformationWindow htmlText="Hier liegt #{cardModel.stadt}!"/>
                 </m:marker>
             </m:map>
            </p:panel>    
        </h:form>
    </h:body>
</html>

WanderWIKI/web/resources/basics/menubarHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* erstellt am 08.06.2014
* Menübar -> sichtbar auf allen Seiten  
* Verantwortlich: Andre Hantke
* Version 1.0
********************************************************/-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    <f:loadBundle id="languageBase" basename="#{internationalButton.value}" var="messages"/>
    <h:head>
        <title>Menubar</title>
         <meta charset="utf-8"></meta>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></meta>
        <meta name="description" content=""></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>  
    </h:head>
    <h:body>
    
        <ui:composition>
       <h:form>
           <p:menubar id="menubar" autoDisplay="true">
              <p:menuitem value="#{messages['Startseite']}" url="#{navigationBean.goToStartseite()}"/>
      <!--        <p:menuitem value="#{messages['Wiki']}" url="#{navigationBean.goToWiki()}"/>
              <p:menuitem value="#{messages['Karte']}" url="#{navigationBean.goToKarte()}"/>-->
              <p:menuitem value="#{messages['Hilfe']}" url="#{navigationBean.goToHilfe()}"/>
            </p:menubar>
        </h:form>  
            </ui:composition>
    </h:body>
</html>

WanderWIKI/web/resources/basics/titleHeader.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE html>
<!--
/*******************************************************
* WanderApp
* erstellt am 08.06.2014
* Titel Header der Webseite (links oben)
* Wandern, Wander im westlichen Münsterland
* Verantwortlich: Andre Hantke
* Editiert: Claas Schlonsok
* Version 0.6
********************************************************/-->
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:p="http://primefaces.org/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">   
    
    <f:loadBundle id="languageBase" basename="#{internationalButton.value}" var="messages"/>
    <h:head>
        <meta charset="utf-8"></meta>
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1"></meta>
        <meta name="description" content=""></meta>
        <meta name="viewport" content="width=device-width, initial-scale=1"></meta>  
       
    </h:head>
    <h:body>
        <ui:composition>
            <p:panel style="border-color: transparent; height: 90px;">
                <p:graphicImage library="Images" value="/resources/Images/wapp_logo.png" height="40px"></p:graphicImage>
                <h:outputText value="#{messages['WanderWIKI']}" style="font-size: 24px;"/><br/>
                <h:outputText value="#{messages['Wandern']}" style="font-size: 18px;"/>
            </p:panel>
        </ui:composition>
    </h:body>

</html>