WanderWIKI/src/java/org/wanderWiki/entities/Comments.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.wanderWiki.entities;

import java.io.Serializable;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 *
 * @author Stephan
 */
@Entity
@Table(name = "comments")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Comments.findAll", query = "SELECT c FROM Comments c"),
    @NamedQuery(name = "Comments.findByIdComments", query = "SELECT c FROM Comments c WHERE c.idComments = :idComments"),
    @NamedQuery(name = "Comments.findByRating", query = "SELECT c FROM Comments c WHERE c.rating = :rating"),
    @NamedQuery(name = "Comments.findByTime", query = "SELECT c FROM Comments c WHERE c.time = :time")})
public class Comments implements Serializable {
    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "idComments")
    private Integer idComments;
    @Column(name = "rating")
    @Min(0) @Max(5)
    private long rating;
    @Lob
    @Size(max = 2147483647)
    @Column(name = "text")
    private String text;
    @Column(name = "time")
    @Temporal(TemporalType.TIMESTAMP)
    private Date time;
    @JoinColumn(name = "idPlace", referencedColumnName = "idPlaces")
    @ManyToOne
    private Places idPlace;
    @JoinColumn(name = "idRoute", referencedColumnName = "idRoutes")
    @ManyToOne
    private Routes idRoute;
    @JoinColumn(name = "idUser", referencedColumnName = "userid")
    @ManyToOne
    private Users idUser;

    public Comments() {
        this.time = new Date();
    }

    public Comments(Integer idComments) {
        this.idComments = idComments;
    }

    public Integer getIdComments() {
        return idComments;
    }

    public void setIdComments(Integer idComments) {
        this.idComments = idComments;
    }

    public long getRating() {
        return rating;
    }

    public void setRating(long rating) {
        this.rating = rating;
    }

    public String getText() {
        return text;
    }

    public void setText(String text) {
        this.text = text;
    }

    public Date getTime() {
        return time;
    }

    public void setTime(Date time) {
        this.time = time;
    }

    public Places getIdPlace() {
        return idPlace;
    }

    public void setIdPlace(Places idPlace) {
        this.idPlace = idPlace;
    }

    public Routes getIdRoute() {
        return idRoute;
    }

    public void setIdRoute(Routes idRoute) {
        this.idRoute = idRoute;
    }

    public Users getIdUser() {
        return idUser;
    }

    public void setIdUser(Users idUser) {
        this.idUser = idUser;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (idComments != null ? idComments.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Comments)) {
            return false;
        }
        Comments other = (Comments) object;
        if ((this.idComments == null && other.idComments != null) || (this.idComments != null && !this.idComments.equals(other.idComments))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "org.wanderWiki.entities.Comments[ idComments=" + idComments + " ]";
    }
    
}

WanderWIKI/src/java/org/wanderWiki/jsf/CommentsController.java
/*******************************************************
* WanderApp
* erstellt am 18.03.2015
* JSF Controller für den Adminbereich von Kommentaren .
* Verantwortlich: Claas Schlonsok
* Version 0.1
********************************************************/
package org.wanderWiki.jsf;

import org.wanderWiki.entities.Comments;
import org.wanderWiki.jsf.util.JsfUtil;
import org.wanderWiki.jsf.util.JsfUtil.PersistAction;
import org.wanderWiki.jpa.CommentsFacade;

import java.io.Serializable;
import java.util.List;
import java.util.ResourceBundle;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.ejb.EJB;
import javax.ejb.EJBException;
import javax.inject.Named;

import javax.faces.bean.ManagedBean;
import javax.faces.bean.SessionScoped;
import javax.faces.component.UIComponent;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;

@ManagedBean(name = "commentsController")
@SessionScoped
public class CommentsController implements Serializable {


    private org.wanderWiki.jpa.CommentsFacade ejbFacade;
    private List<Comments> items = null;
    private Comments selected;

    public CommentsController() {
        ejbFacade = new CommentsFacade();
    }

    public Comments getSelected() {
        return selected;
    }

    public void setSelected(Comments selected) {
        this.selected = selected;
    }

    protected void setEmbeddableKeys() {
    }

    protected void initializeEmbeddableKey() {
    }

    private CommentsFacade getFacade() {
        return ejbFacade;
    }

    public Comments prepareCreate() {
        selected = new Comments();
        initializeEmbeddableKey();
        return selected;
    }

    public void create() {
        persist(PersistAction.CREATE, ResourceBundle.getBundle("/org.wanderWiki.language/messages").getString("CommentsCreated"));
        if (!JsfUtil.isValidationFailed()) {
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public void update() {
        persist(PersistAction.UPDATE, ResourceBundle.getBundle("/org.wanderWiki.language/messages").getString("CommentsUpdated"));
    }

    public void destroy() {
        persist(PersistAction.DELETE, ResourceBundle.getBundle("/org.wanderWiki.language/messages").getString("CommentsDeleted"));
        if (!JsfUtil.isValidationFailed()) {
            selected = null; // Remove selection
            items = null;    // Invalidate list of items to trigger re-query.
        }
    }

    public List<Comments> getItems() {
        if (items == null) {
            items = getFacade().findAll();
        }
        return items;
    }

    private void persist(PersistAction persistAction, String successMessage) {
        if (selected != null) {
            setEmbeddableKeys();
            try {
                if (persistAction != PersistAction.DELETE) {
                    getFacade().edit(selected);
                } else {
                    getFacade().remove(selected);
                }
                JsfUtil.addSuccessMessage(successMessage);
            } catch (EJBException ex) {
                String msg = "";
                Throwable cause = ex.getCause();
                if (cause != null) {
                    msg = cause.getLocalizedMessage();
                }
                if (msg.length() > 0) {
                    JsfUtil.addErrorMessage(msg);
                } else {
                    JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/org.wanderWiki.language/messages").getString("PersistenceErrorOccured"));
                }
            } catch (Exception ex) {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, null, ex);
                JsfUtil.addErrorMessage(ex, ResourceBundle.getBundle("/org.wanderWiki.language/messages").getString("PersistenceErrorOccured"));
            }
        }
    }

    public Comments getComments(java.lang.Integer id) {
        return getFacade().find(id);
    }

    public List<Comments> getItemsAvailableSelectMany() {
        return getFacade().findAll();
    }

    public List<Comments> getItemsAvailableSelectOne() {
        return getFacade().findAll();
    }

    @FacesConverter(forClass = Comments.class)
    public static class CommentsControllerConverter implements Converter {

        @Override
        public Object getAsObject(FacesContext facesContext, UIComponent component, String value) {
            if (value == null || value.length() == 0) {
                return null;
            }
            CommentsController controller = (CommentsController) facesContext.getApplication().getELResolver().
                    getValue(facesContext.getELContext(), null, "commentsController");
            return controller.getComments(getKey(value));
        }

        java.lang.Integer getKey(String value) {
            java.lang.Integer key;
            key = Integer.valueOf(value);
            return key;
        }

        String getStringKey(java.lang.Integer value) {
            StringBuilder sb = new StringBuilder();
            sb.append(value);
            return sb.toString();
        }

        @Override
        public String getAsString(FacesContext facesContext, UIComponent component, Object object) {
            if (object == null) {
                return null;
            }
            if (object instanceof Comments) {
                Comments o = (Comments) object;
                return getStringKey(o.getIdComments());
            } else {
                Logger.getLogger(this.getClass().getName()).log(Level.SEVERE, "object {0} is of type {1}; expected type: {2}", new Object[]{object, object.getClass().getName(), Comments.class.getName()});
                return null;
            }
        }

    }

}

WanderWIKI/web/admin/comments/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CommentsCreateDlg" widgetVar="CommentsCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{messages.CreateCommentsTitle}">
            <h:form id="CommentsCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{commentsController.selected != null}">
                        <p:outputLabel value="#{messages.CreateCommentsLabel_idComments}" for="idComments" />
                        <p:inputText id="idComments" value="#{commentsController.selected.idComments}" title="#{messages.CreateCommentsTitle_idComments}" required="false" disabled="true" requiredMessage="#{messages.CreateCommentsRequiredMessage_idComments}"/>
                        <p:outputLabel value="#{messages.CreateCommentsLabel_text}" for="text" />
                        <p:inputTextarea rows="4" cols="30" id="text" value="#{commentsController.selected.text}" title="#{messages.CreateCommentsTitle_text}" />
                        <p:outputLabel value="#{messages.CreateCommentsLabel_time}" for="time" />
                        <p:calendar id="time" pattern="MM/dd/yyyy HH:mm:ss" value="#{commentsController.selected.time}" title="#{messages.EditCommentsTitle_time}"  showOn="button"/>
                        <p:outputLabel value="#{messages.CreateCommentsLabel_idPlace}" for="idPlace" />
                        <p:selectOneMenu id="idPlace" value="#{commentsController.selected.idPlace}" >
                            <f:selectItem itemLabel="#{messages.SelectOneMessage}"/>
                            <f:selectItems value="#{placesController.itemsAvailableSelectOne}"
                                           var="idPlaceItem"
                                           itemValue="#{idPlaceItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{messages.CreateCommentsLabel_idRoute}" for="idRoute" />
                        <p:selectOneMenu id="idRoute" value="#{commentsController.selected.idRoute}" >
                            <f:selectItem itemLabel="#{messages.SelectOneMessage}"/>
                            <f:selectItems value="#{routesController.itemsAvailableSelectOne}"
                                           var="idRouteItem"
                                           itemValue="#{idRouteItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{messages.CreateCommentsLabel_idUser}" for="idUser" />
                        <p:selectOneMenu id="idUser" value="#{commentsController.selected.idUser}" >
                            
                            <f:selectItems value="#{usersController.itemsAvailableSelectOne}"
                                           var="idUserItem"
                                           itemValue="#{idUserItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{commentsController.create}" value="#{messages.Save}" update="display,:CommentsListForm:datalist,:growl" oncomplete="handleSubmit(args,'CommentsCreateDialog');"/>
                    <p:commandButton value="#{messages.Cancel}" onclick="CommentsCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

WanderWIKI/web/admin/comments/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CommentsEditDlg" widgetVar="CommentsEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{messages.EditCommentsTitle}">
            <h:form id="CommentsEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{commentsController.selected != null}">
                        <p:outputLabel value="#{messages.EditCommentsLabel_idComments}" for="idComments" />
                        <p:inputText id="idComments" value="#{commentsController.selected.idComments}" title="#{messages.EditCommentsTitle_idComments}" disabled="true" required="true" requiredMessage="#{messages.EditCommentsRequiredMessage_idComments}"/>
                        <p:outputLabel value="#{messages.EditCommentsLabel_text}" for="text" />
                        <p:inputTextarea rows="4" cols="30" id="text" value="#{commentsController.selected.text}" title="#{messages.EditCommentsTitle_text}" />
                        <p:outputLabel value="#{messages.EditCommentsLabel_time}" for="time" />
                        <p:calendar id="time" pattern="MM/dd/yyyy HH:mm:ss" value="#{commentsController.selected.time}" title="#{messages.EditCommentsTitle_time}"  showOn="button"/>
                        <p:outputLabel value="#{messages.EditCommentsLabel_idPlace}" for="idPlace" />
                        <p:selectOneMenu id="idPlace" value="#{commentsController.selected.idPlace}" >
                            <f:selectItem itemLabel="#{messages.SelectOneMessage}"/>
                            <f:selectItems value="#{placesController.itemsAvailableSelectOne}"
                                           var="idPlaceItem"
                                           itemValue="#{idPlaceItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{messages.EditCommentsLabel_idRoute}" for="idRoute" />
                        <p:selectOneMenu id="idRoute" value="#{commentsController.selected.idRoute}" >
                            <f:selectItem itemLabel="#{messages.SelectOneMessage}"/>
                            <f:selectItems value="#{routesController.itemsAvailableSelectOne}"
                                           var="idRouteItem"
                                           itemValue="#{idRouteItem}"/>
                        </p:selectOneMenu>
                        <p:outputLabel value="#{messages.EditCommentsLabel_idUser}" for="idUser" />
                        <p:selectOneMenu id="idUser" value="#{commentsController.selected.idUser}" >
                            <f:selectItem itemLabel="#{messages.SelectOneMessage}"/>
                            <f:selectItems value="#{usersController.itemsAvailableSelectOne}"
                                           var="idUserItem"
                                           itemValue="#{idUserItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{commentsController.update}" value="#{messages.Save}" update="display,:CommentsListForm:datalist,:growl" oncomplete="handleSubmit(args, 'CommentsEditDialog');"/>
                    <p:commandButton value="#{messages.Cancel}" onclick="CommentsEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

WanderWIKI/web/admin/comments/List.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition template="/resources/template.xhtml">

        <ui:define name="imheader">
          
            <!--<h:outputStylesheet name="./css/jsfcrud.css" />-->
            <h:outputScript name="./css/jsfcrud.js"  target="head" />

        </ui:define>

        <ui:define name="content">
            <h:form id="CommentsListForm">
                <p:panel >
                    <p:dataTable id="datalist" value="#{commentsController.items}" var="item"
                                 selectionMode="single" selection="#{commentsController.selected}"
                                 paginator="true"
                                 rowKey="#{item.idComments}"
                                 rows="10"
                                 rowsPerPageTemplate="10,20,30,40,50"
                                 >

                        <p:ajax event="rowSelect"   update="createButton viewButton editButton deleteButton"/>
                        <p:ajax event="rowUnselect" update="createButton viewButton editButton deleteButton"/>

                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{messages.ListCommentsTitle_idComments}"/>
                            </f:facet>
                            <h:outputText value="#{item.idComments}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{messages.ListCommentsTitle_text}"/>
                            </f:facet>
                            <h:outputText value="#{item.text}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{messages.ListCommentsTitle_time}"/>
                            </f:facet>
                            <h:outputText value="#{item.time}">
                                <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                            </h:outputText>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{messages.ListCommentsTitle_idPlace}"/>
                            </f:facet>
                            <h:outputText value="#{item.idPlace}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{messages.ListCommentsTitle_idRoute}"/>
                            </f:facet>
                            <h:outputText value="#{item.idRoute}"/>
                        </p:column>
                        <p:column>
                            <f:facet name="header">
                                <h:outputText value="#{messages.ListCommentsTitle_idUser}"/>
                            </f:facet>
                            <h:outputText value="#{item.idUser}"/>
                        </p:column>
                        <f:facet name="footer">
                            <p:commandButton id="createButton" icon="ui-icon-plus"   value="#{messages.Create}" actionListener="#{commentsController.prepareCreate}" update=":CommentsCreateForm" oncomplete="PF('CommentsCreateDialog').show()"/>
                            <p:commandButton id="viewButton"   icon="ui-icon-search" value="#{messages.View}" update=":CommentsViewForm" oncomplete="PF('CommentsViewDialog').show()" disabled="#{empty commentsController.selected}"/>
                            <p:commandButton id="editButton"   icon="ui-icon-pencil" value="#{messages.Edit}" update=":CommentsEditForm" oncomplete="PF('CommentsEditDialog').show()" disabled="#{empty commentsController.selected}"/>
                            <p:commandButton id="deleteButton" icon="ui-icon-trash"  value="#{messages.Delete}" actionListener="#{commentsController.destroy}" update=":growl,datalist" disabled="#{empty commentsController.selected}"/>
                        </f:facet>
                    </p:dataTable>
                </p:panel>
            </h:form>

            <ui:include src="Create.xhtml"/>
            <ui:include src="Edit.xhtml"/>
            <ui:include src="View.xhtml"/>
        </ui:define>
    </ui:composition>

</html>

WanderWIKI/web/admin/comments/View.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="CommentsViewDlg" widgetVar="CommentsViewDialog" modal="true" resizable="false" appendTo="@(body)" header="#{messages.ViewCommentsTitle}">
            <h:form id="CommentsViewForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{commentsController.selected != null}">
                        <h:outputText value="#{messages.ViewCommentsLabel_idComments}"/>
                        <h:outputText value="#{commentsController.selected.idComments}" title="#{messages.ViewCommentsTitle_idComments}"/>
                        <h:outputText value="#{messages.ViewCommentsLabel_text}"/>
                        <h:outputText value="#{commentsController.selected.text}" title="#{messages.ViewCommentsTitle_text}"/>
                        <h:outputText value="#{messages.ViewCommentsLabel_time}"/>
                        <h:outputText value="#{commentsController.selected.time}" title="#{messages.ViewCommentsTitle_time}">
                            <f:convertDateTime pattern="MM/dd/yyyy HH:mm:ss" />
                        </h:outputText>
                        <h:outputText value="#{messages.ViewCommentsLabel_idPlace}"/>
                        <h:outputText value="#{commentsController.selected.idPlace}" title="#{messages.ViewCommentsTitle_idPlace}"/>
                        <h:outputText value="#{messages.ViewCommentsLabel_idRoute}"/>
                        <h:outputText value="#{commentsController.selected.idRoute}" title="#{messages.ViewCommentsTitle_idRoute}"/>
                        <h:outputText value="#{messages.ViewCommentsLabel_idUser}"/>
                        <h:outputText value="#{commentsController.selected.idUser}" title="#{messages.ViewCommentsTitle_idUser}"/>
                    </p:panelGrid>
                    <p:commandButton value="#{messages.Close}" onclick="CommentsViewDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>